### ISSUE TITLE
[Bug] Running through Flatpak crashes on segfault

### ISSUE THREAD

**Issue by djkato** [Vencord/Vesktop#1003]
### Operating System

Fedora 40

### Linux Only ~ Desktop Environment

Wayland

### Package Type

Flatpak

### What happens when the bug or crash occurs?

App just never starts

### What is the expected behaviour?

Run

### How do you recreate this bug or crash?

1. `flatpak run dev.vencord.Vesktop`
2. crash

### Debug Logs

```
djkato@worktop ~/> flatpak run dev.vencord.Vesktop
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-speech-dispatcher --ozone-platform-hint=auto --enable-wayland-ime
[3:1212/215616.459684:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
/app/bin/startvesktop: line 27:     3 Segmentation fault      (core dumped) zypak-wrapper /app/bin/vesktop/vesktop.bin "${FLAGS[@]}" "$@"
djkato@worktop ~/ [SIGSEGV]>
```

Looks like the flatpak and appimage envs got mixed up or smt during build?

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
system issue

https://www.google.com/search?q=Failed+to+connect+to+the+bus%3A+Failed+to+connect+to+socket+%2Frun%2Fdbus%2Fsystem_bus_socket%3A+No+such+file+or+directory&client=chrome

**Comment by fuchs-fabian** [comment]
I can confirm that it was really due to the system configuration. More precisely, the integrated GPU. My CPU (i7-12700k) contains a graphics unit...

This led to this error. The error message was somewhat misleading.

Specifically, I had to change the following in the UEFI at MSI:

Disable **IGD Multi-Monitor**!

![image](https://github.com/user-attachments/assets/c929d999-3d57-42a5-a166-9323eaa6b61b)
![image](https://github.com/user-attachments/assets/f9d8f7f4-7681-45c5-81a4-c96aa8b5e22e)

> Even if, strangely enough, I have only experienced this with Vesktop so far, this solution should also prevent problems with other applications.
