### ISSUE TITLE
[Bug] CPU usage increasing as screensharing goes

### ISSUE THREAD

**Issue by Oxygels** [Vencord/Vesktop#1028]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

KDE on Wayland

### Package Type

AppImage (official) and RPM (from AUR)

### What happens when the bug or crash occurs?

When screensharing, the CPU usage of electron increases during the stream
It takes like 8h for me to reach 100% CPU usage but it does exist.

I suspect this to be an electron upstream issue but I can't be sure.

I have an AMD 7800XT and this happens with or without HW acceleration (in Discord settings)

### What is the expected behaviour?

I expect Discord to have a "constant" CPU usage and not slowly increase to 100%.

### How do you recreate this bug or crash?

1. Start a screenshare
2. Pick a window or a screen
3. Pick the Smoothness or Clarity preset (I noticed it didn't happen sometimes with the Clarity preset) 
4. Wait 1-2h and the CPU usage will already have increased by a significant margin (10-20%)

### Debug Logs

No relevant line, unfortunately :'(

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
This is most likely indeed an electron or even chromium issue. I don't think there is much we can do unfortunately :(

I advise you to try to reproduce this in Chrome (visit discord.com/app in chrome) and electron (this is gonna be a bit hard especially if you're not a programmer) and then report it to the one that's at fault

**Comment by Oxygels** [comment]
Thank you for your advice, I will do that!
And thank you for developing Vesktop :rocket:

**Comment by DBosley** [comment]
I think I found the root cause of this. Same symptom here: CPU starts low when the share begins and climbs until the machine is crawling a couple hours later. Restarting the share resets it every time.

Setup: Vesktop 1.6.5 (Electron 40.4 / Chromium 144), Arch, KDE Plasma on Wayland, PipeWire capture through xdg-desktop-portal-kde, 3440x1440 at ~45fps, software encode, 16 core Ryzen.

I sampled the whole vesktop process tree every 20 seconds during a long share (per-thread CPU from /proc, RSS, and voluntary context switch rates on the capture threads as an fps proxy). The interesting part is that the renderer CPU does not creep smoothly. It increases in discrete steps of roughly 55 to 65 percentage points, exactly every 300 seconds. I logged eight consecutive steps landing 300s apart to the second (17:25:45, 17:30:45, 17:35:45 and so on). Once I spotted the cadence I predicted the next few steps ahead of time and they arrived on schedule. After about two hours the renderer was above 900% CPU with load average around 25.

Meanwhile capture frame rate stays constant the whole time (the desktopCaptureThread wake rate holds at 43 to 48 per second) and RSS stays flat around 900MB. So it is not the encoder adapting upward and it is not a memory leak. Nearly all the burn is in ThreadPoolForegroundWorker threads: of 13 CPU hours the renderer accumulated in one session, 11.75 were in the generic pool, while the actual codec threads used 14 seconds total. That pool is where Chromium runs libyuv frame format conversions.

The 300 second interval matches Discord's stream preview uploader. The client grabs a thumbnail of the stream every 5 minutes and POSTs it to /api/v9/streams/{key}/preview. My read of the data is that each grab registers a frame sink on the capture track and never unregisters it. In webrtc every registered sink receives every frame and pays its own BGRA to I420 conversion, which at 3440x1440 and 45fps costs about half a core. So N preview ticks leave N permanent converters chewing on every frame. That fits everything observed: steps on a 300s clock, constant fps, flat memory (a leaked sink is just a callback registration, not a buffer), the burn sitting in the generic pool rather than codec or capture threads, and the share restart reset, since restarting throws away the track and its sinks.

Two experiments to narrow it down. Unchecking "Show My Screen Share" and restarting the share halves the step size (steps of 25 to 34 points instead of 55 to 65) but the 5 minute steps keep coming, so the local self preview and the preview uploader are separate frame consumers and the uploader is the one that leaks. And a share restart drops the renderer back to ~45% instantly, every time.

Happy to share the raw sample logs or run more instrumentation if useful. If someone wants to confirm from the Chromium side, chrome://tracing with the webrtc category during a share should show the conversion tasks multiplying after each 5 minute mark.

PR to update one of the default plugins to fix this:
https://github.com/Vendicated/Vencord/pull/4390
