### ISSUE TITLE
Add package to Homebrew

### ISSUE THREAD

**Issue by doinkythederp** [Vencord/Vesktop#172]
I'd really like to be able to install this on macOS via [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) - `brew install vesktop`. This would require making a pull request to the Homebrew Cask repository that adds Vesktop as a package.

https://docs.brew.sh/Adding-Software-to-Homebrew#casks

**Comment by doinkythederp** [comment]
Here's a cask file I worked on for a bit:
```rb
cask "vesktop" do
  version "0.4.1"
  sha256 on_arch_conditional arm: "c9f772bd5f2a6d04290c86850c0bd0984904ccb9fbc1998fac04b737aabbe9d5",
    intel: "0c14ef9a6681093fa58f6ee8aa9432f3395602870bee2251af8497481b782575"

  url on_arch_conditional arm: "https://github.com/Vencord/Vesktop/releases/download/v#{version}/Vesktop-#{version}-arm64.dmg",
    intel: "https://github.com/Vencord/Vesktop/releases/download/v#{version}/Vesktop-#{version}.dmg"

  name "Vesktop"
  desc "Vesktop gives you the performance of web Discord and the comfort of Discord Desktop"
  homepage "https://github.com/Vencord/Vesktop"

  app "Vesktop.app"

  livecheck do
    url "https://github.com/Vencord/Vesktop.git"
    regex(/^v?(\d+(?:\.\d+)+)$/i)
  end
end
```
It doesn't work because Vesktop.app does not have a code signature.

**Comment by olivertzeng** [comment]
+1 would like that to happen!

**Comment by lewisakura** [comment]
[macOS Gatekeeper will prevent this from working properly](https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer), and we aren't spending the money on an Apple Developer Account at this time because it's such a waste for a false sense of security. It sounds like this will cause a lot of annoyance for Homebrew users if we don't sign.

**Comment by olivertzeng** [comment]
> [macOS Gatekeeper will prevent this from working properly](https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer), and we aren't spending the money on an Apple Developer Account at this time because it's such a waste for a false sense of security. It sounds like this will cause a lot of annoyance for Homebrew users if we don't sign.

At least you can open them, because upgrading them with releases is a pain

**Comment by olivertzeng** [comment]
too many clicks

**Comment by doinkythederp** [comment]
Homebrew may actually make Vesktop easier to install because it has the --no-quarantine flag to turn off macOS Gatekeeper.

**Comment by Git-North** [comment]
> Homebrew may actually make Vesktop easier to install because it has the --no-quarantine flag to turn off macOS Gatekeeper.

+1 this would make installing incredibly easy.

**Comment by EvilSquirrelGuy** [comment]
+1 this would be super convenient to have

**Comment by ZirixCZ** [comment]
@doinkythederp I took your formulae and updated it a little. Went through the process of verifying we're eligible to be in their repositories and found we're not since the Vekstop.app is not signed. Until then, I created a tap that I'll keep up to date. You can find it here: https://github.com/ZirixCZ/homebrew-vesktop

Installation is `brew install --cask zirixcz/vesktop/vesktop`

I am not sure how to make it a one cask repository (to achieve username/vesktop). If you feel like improving it, feel free to make a PR. Also perhaps this should be under Vencord, but for now it is not an official thing, but perhaps it could be one of the official ways to install it in the future, since it is way easier if already familiar with brew.

**Comment by Yanderuri** [comment]
Somewhat relevant, Alacritty exists as a cask and I don't think they sign?

<img width="245" alt="image" src="https://github.com/Vencord/Vesktop/assets/50468506/9a31fc85-dc59-4afd-90ee-75a3e3941966">

**Comment by Vendicated** [comment]
vesktop is signed now, so this should be resolved?

**Comment by doinkythederp** [comment]
I don't think this is ready to be resolved; I was hoping for an official Homebrew tap or the option to run `brew install vesktop` to install Vesktop.

**Comment by olivertzeng** [comment]
yup

**Comment by Vendicated** [comment]
i was talking about the signing issue. there will be no official homebrew package so if you want it you can make it yourself

**Comment by olivertzeng** [comment]
> i was talking about the signing issue. there will be no official homebrew package so if you want it you can make it yourself

oh ok

**Comment by olivertzeng** [comment]
> i was talking about the signing issue. there will be no official homebrew package so if you want it you can make it yourself

i think that he's probably talking about the brew package

if this project will not provide an official brew package, you should probably close this issue to not planned

**Comment by RokeJulianLockhart** [comment]
> https://github.com/Vencord/Vesktop/issues/172#event-13256427970

@Vendicated, is this https://github.com/Vencord/Vesktop/issues?q=reason%3A%22not+planned%22 because as https://github.com/Vencord/Vesktop/issues/172#event-13256427970 requires, this isn't notarised? I expect you don't want to pay for a certificate?

**Comment by adarah** [comment]
[Aerospace](https://github.com/nikitabobko/AeroSpace?tab=readme-ov-file#installation) is not notarized either, but I don't get an installation warning because their "[Homebrew installation script](https://github.com/nikitabobko/homebrew-tap/blob/main/Casks/aerospace.rb) is configured to automatically delete com.apple.quarantine attribute".

Maybe encored could consider creating a tap under the `vencord` namespace? Like `vencord/tap/vesktop`

**Comment by christmaswreath** [comment]
sorry for kinda necroing but this would be convenient as for me vencord has a tendency of breaking and to reinstall the app it would be as simple as `brew reinstall vesktop` instead of downloading it, applying the discord icon, renaming it to discord, and then launching it.

**Comment by TrStans606** [comment]
Librewolf is not signed and is included in the official cask repository. It's convenient as using the --no-quarantine flag allows the app to run unsigned without running the command myself. I don't know if this is a recent change but not being notarized should not be an issue with brew as many brew apps are un-notarized.

Here is the page for librewolf: https://formulae.brew.sh/cask/librewolf
