### ISSUE TITLE
Vesktop "reloads" when regaining focus

### ISSUE THREAD

**Issue by LessThanGreaterThan** [Vencord/Vesktop#277]
once i minimize vesktop and pull it back in focus it goes to the loading animation and shows as usual once its back open.
while its minimized it also does not seem to receive messages and doesn't give notifications etc.

**Comment by Four-hundred** [comment]
In my case, it reloads everything upon gaining focus without any loading animations, simply all nicknames in the chat turn white for a brief moment, and I also stop receiving notifications until I pull discord back into focus. This happens only when I launch any game, and the only way to return the normal behavior is to restart Vesktop.

The only workaround I'm testing right now is to disable Game Mode (Win + I > Gaming > Game Mode), it seems to mitigate the issue for now. Try this out.

**Comment by lewisakura** [comment]
this sounds like windows is suspending the process in the background, thus when you bring it back to the foreground it will allow the process to resume, at which point it will need to reconnect to discord since it has timed out at this point (discord requires a constant connection to keep itself alive, hence the reloading). there is no fix for this on our end, really.
