### ISSUE TITLE
flatpak can't upload files unless it's an image copied to the clipboard 

### ISSUE THREAD

**Issue by skweed0** [Vencord/Vesktop#313]
this is only a problem with the flatpak it works fine for me with the appimage

**Comment by Vendicated** [comment]
please provide more info. how are you trying to upload, what happens, are there any errors. attach a video

**Comment by Sphirye** [comment]
> this is only a problem with the flatpak it works fine for me with the appimage

This sounds more like a flatpak permissions issue since this happened to me when i started storing my stuff in a external drive, remember that flatpak apps will just have access to default public home folders like Downloads, Pictures, Music and Videos; this means that Vesktop (as a flatpak app) wont be able to access anything else but these folders (unless you attach the file manually using the plus button in chat)

Try `flatpak override --filesystem=<route_to_your_wanted_folder> dev.vencord.Vesktop` or use Flatseal to manage this kind of permissions
