### ISSUE TITLE
Vesktop uses more resources than Discord app on Windows 11 

### ISSUE THREAD

**Issue by AdvitSphinX** [Vencord/Vesktop#429]
**Describe the bug**
Vesktop uses more resources than Discord app on Windows 11, thats all :)

**To Reproduce**
Just open both app and compare. 

**Expected behavior**
Expected to use less resources than Discord app.

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/139687689/4050d635-fb1c-4801-b156-39b932414516)

**Desktop (please complete the following information):**
 - OS/Distro: [Windows]
 - Version: [11]

**Comment by Vendicated** [comment]
this report is useless. you have provided 0 context, nor done any own research on why this could be the case

**Comment by AdvitSphinX** [comment]
What context you want? The vesktop is using more ram as compared to discord. But it is said that vesktop uses more ram than the discord's own app.

**Comment by nin0-dev** [comment]
All you gave is a task manager screenshot, without knowing how many plugins you have on for each app, or if you have a theme

a lot of factors can actually have an influence on performance, like right now I opened task manager with the exact same config on both vesktop and the official app, and the official app uses more RAM

**Comment by AdvitSphinX** [comment]
the one I have given is also with the same configurations on both the apps and the vesktop seems to use 2x ram compared to the official app. (sorry fo r not telling that yearlier, I'm new & thanks)

**Comment by Vendicated** [comment]
if you actually want to report memory usage and have it be meaningful, you need to share as much info as possible, and check the memory profile

in any case, vesktop makes no attempt at using less memory than the official Discord app. that is not possible, because they both use the same web app (discord.com/app). their usage will be fairly similar, with vesktop usually using slightly less.
