### ISSUE TITLE
Game Overlay

### ISSUE THREAD

**Issue by DastardlyDino** [Vencord/Vesktop#444]
I really like the Game Overlay feature that stock discord has. Is this something that can be added to Vesktop?

https://support.discord.com/hc/en-us/articles/217659737-Game-Overlay-101

![image](https://github.com/Vencord/Vesktop/assets/47339617/da28a3bf-376a-4b9b-8140-e51b3051d89d)

**Comment by Grafaffel** [comment]
Technically you could open a new transparent window, but my concern would be, that the game loses focus. The Native Discord Game Overlay is prob injecting something into the games executable (from looking at the support article).

**Comment by Vendicated** [comment]
absolutely out of scope for vesktop. that would be a lot of effort. just use normal discord if you need features like this

**Comment by Hacksore** [comment]
Hi folks 👋

Overlayed seems like a good middle ground for this but I'm unsure if Overlayed will work ith Vesktop.

@aqtoo opened https://github.com/Hacksore/overlayed/issues/78 which is asking to support Vesktop. However, I'm unsure of if it supports the [RPC API via websockets](https://discord.com/developers/docs/topics/rpc#connecting) so if we can clarify that would be awesome!

Otherwise if it's a missing feature do we need to open a feature request?

**Comment by Vendicated** [comment]
Hi! it does support RPC via the arRPC project, but it's limited to rich presence. any more advanced functionality is not supported, so it will likely not be sufficient for Overlayed

See also https://github.com/OpenAsar/arrpc/issues/18

the best way to go about this would be to fork arrpc and make it integrate it more deeply with vesktop / other custom clients like armcord, but that would be considerable effort
