### ISSUE TITLE
Add option to use default Discord tray icon instead of Vesktop's custom one

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#448]

**Comment by Vendicated** [comment]
trademark infringement.

**Comment by FelipeFMA** [comment]
> Would it be possible to add a command line option so the user can choose the name/path of the icon the application should use?
> 
> This way, it becomes possible to use any icon installed on the user's system, without adding new icon(s) to Vesktop itself.

This would be awesome, the vesktop logo doesn't match with most themes

![image](https://github.com/Vencord/Vesktop/assets/30672253/de486a17-bd01-48a3-8266-90f4475a95f1)

**Comment by TotalChaos05** [comment]
@FelipeFMA You can do it if you overwrite build/icon.png with the discord icon

**Comment by PolisanTheEasyNick** [comment]
> @TotalChaos05 Where are static/icon.ico and static/icon.png located? Thanks in advance.

You can find folder "static" literally in project root folder

**Comment by shvedes** [comment]
The problem with static icons is that shitty framework called electron use `.svg` format ([link 1](https://github.com/electron/electron/issues/9642), [link 2](https://www.electronjs.org/docs/latest/api/native-image#supported-formats)). Because of this, you can forget about non-blurry monochrome tray icons for both light and dark modes on Linux systems.
