### ISSUE TITLE
Vesktop main window is unable to snap on some Wayland GNOME desktop setups

### ISSUE THREAD

**Issue by justin13888** [Vencord/Vesktop#453]
I expect the Vesktop window to be snappable when dragged to the edge of my screen. In my multi-monitor setup on Wayland GNOME, it snaps on my main monitor but not my upper monitor.

Occasionally, when the window happens to open in my upper monitor, it manages to snap but as soon as I drag the window back to my main monitor and then back up to second monitor, it stops working.

My suspicion is related to the window resolution size being affected by different window fractional scaling factors in Wayland.

**To Reproduce**

- Be on GNOME Wayland on Linux
- Have two monitors (might require different effective pixel size (i.e. native monitor resolution / scale factor) between monitors)

**Expected behavior**

Vesktop window should snap the same way like how it does on main monitor.

**Screenshots**

![image](https://github.com/Vencord/Vesktop/assets/20733699/782a2b7f-ce4c-4a1e-a26a-e215f41e41ce)
The blue in background is the snapping visual effect from GNOME

**Desktop (please complete the following information):**
- OS: Fedora 39 Workstation
- Desktop environment: GNOME 45 on Wayland
- Vesktop version: Flatpak version on FlatHub and git master branch

**Additional context**

This is reproducable when running Vesktop with Ozone and Wayland mode on a Wayland desktop. There isn't such an issue on when running on XWayland. I have also only observed it on a multi monitor setup with different resolutions and scale factors.

Using either of these commands is reproducible my system:

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=startvesktop dev.vencord.Vesktop
```
or
```
pnpm start --enable-features=UseOzonePlatform --ozone-platform=wayland
```

Note: `pnpm start` seems to default to XWayland (as expected for Electron) and this issue would not be reproducible in that case

I notice there are some cases when this works

This issue seems localized to particular desktop setups on Wayland GNOME.

Here are some potentially relevant details about my setup:

- Monitors: 

![image](https://github.com/Vencord/Vesktop/assets/20733699/5c6422f2-b1fe-42cc-be0a-e6354e8fa550)
The bottom (primary) monitor is a 5120x1440 120 Hz with 125% scale. Top monitor (monitor 2) is 5120x1440p 60 Hz at 200% scale. Note: GNOME fractional scaling (`scale-monitor-framebuffer`) was enabled.

**Comment by justin13888** [comment]
Would like to also add this problem does not exist in the Windows build of Vesktop on the exact same hardware setup.

**Comment by GregSweats** [comment]
🤔 Hmmm... I came here because I almost punched my monitor in frustration due to **Windows 11 Snap features not working**. Hearing that it is working for @Vendicated just a couple weeks ago makes me hope that it might work for me too!

I've posted a lot here, hope it helps. Will try to keep updated and test but I am horrible at following up on the internetz.

## Next Steps

- [ ] Try `Canary` or `PTB` Discord Branch
- [ ] ???
- [ ] Profit.

## 👋 Hello

Hoping you can help me, @Vendicated 🙏 _(lol btw, might rightfully be _vindicated_ here)_.

- ❌ `[WIN] + [LEFT]` and `[WIN] + [RIGHT]` to **snap the window to one side or the other**. 
- ✅ `[WIN] + [SHIFT} + [LEFT/RIGHT]` to **move the window between monitors**.
- ✅ `[WIN] + [DOWN]` to **minimize window**.
- ❌ **Dragging the Window titlebar** and ***snapping*** it to the left/right/top of a monitor.
- ❌ **Double-click the Window titlebar to maximize** (nor `[WIN] + [UP]` to maximize, nor *dragging/snapping to the top* 😢)

## Compared to "Official" Client

I have not tested with Discord Official Client, since I uninstalled it about 8 hours after installing `Vesktop` 😁.

## Debug Info

**OS Name**:	`Microsoft Windows 11 Pro`
**Version**:	`10.0.22631 Build 22631` (from `System Information (msinfo32)`)
**Vencord Version**: [a66138f](https://github.com/Vendicated/Vencord/commit/a66138f)


## Screenshots

![2024-06-02_19-19-22 Vesktop (4)_Discord__Vencord__User_Settings ZLG4ONTvpi 1804](https://github.com/Vencord/Vesktop/assets/106463642/dc59a3ad-aa8f-4ffe-8d9e-faf89c54d46f)

![2024-06-02_19-20-51 Vesktop (4)_Discord__Vesktop_Settings__User_Settings Yz37ZWk0pp 1806](https://github.com/Vencord/Vesktop/assets/106463642/2bbda024-2648-4ede-a0b2-2ab445cc50b1)

![2024-06-02_19-20-19 Vesktop (4)_Discord__Vesktop_Settings__User_Settings czh4ojEJPQ 1805](https://github.com/Vencord/Vesktop/assets/106463642/f8f888e8-d5d5-43d4-a98a-9123a39d028d)

![2024-06-02_19-24-41 Vesktop (4)_Discord__Updater__User_Settings 1NEsODw9nJ 1807](https://github.com/Vencord/Vesktop/assets/106463642/770d2379-1d19-46bc-9c4f-b644396b347c)

---

## UPDATE1

### Disabled `Discord Titlebar`, no change

![2024-06-02_19-26-30 Vesktop (4)_Discord__Vesktop_Settings__User_Settings dROo4VDhzA 1808](https://github.com/Vencord/Vesktop/assets/106463642/524d2c76-8e00-43db-96ba-57ee8de6e38c)

### Disabled `Disable the window frame` and `Enable window transparency. [sic]`

No change 😔. Also no Windows titlebar though?

![2024-06-02_19-30-58 Vesktop (4)_Discord__Vencord__User_Settings U6dpgmqfyt 1809](https://github.com/Vencord/Vesktop/assets/106463642/8343d928-e1f3-4349-a45a-e390308ce87d)

**Comment by GregSweats** [comment]
# UPDATE2 - Windows Snap Working with Tweaks Below

Happy to report all the shortcuts are working now for me!
Unfortunately small, ugly, title bar at top, but no biggie.

![2024-06-02_19-44-37 Vesktop (4)_Discord__Vesktop_Settings__User_Settings mNLP7Mv4Ov 1811](https://github.com/Vencord/Vesktop/assets/106463642/cff98b8c-19c1-4c87-9837-e0fa9fface52)

**Comment by zrooda** [comment]
Only with "Discord Titlebar" enabled will the app windows be able to snap correctly in Fedora Silverblue. Otherwise the window will be broken until it's maximized once, at which point it will snap and go fullscreen (in streams) fine. Definitely broken out of the box on Gnome.
