### ISSUE TITLE
Vesktop segfault au launch.

### ISSUE THREAD

**Issue by sull324** [Vencord/Vesktop#509]
after updating my arch setup vesktop doesn't launch anymore.

"Job 1, 'vesktop' terminated by signal SIGSEGV (Address boundary error)"

there was already an bug report posted 20 minutes ago by someone else but it got closed not sure why.

**Comment by Star-On-Github** [comment]
`bash
❯ vesktop
[92496:0100/000000.461168:ERROR:broker_posix.cc(41)] Recvmsg error: Connection reset by peer (104)
zsh: segmentation fault (core dumped)  vesktop
`
Terminal output? All that I'm getting.

**Comment by Vendicated** [comment]
it was closed because this has nothing to do with our code. it's an issue with either your system or the electron version you're using (which is not supported by us). find official supported artifacts in releases. if you install differently, you're on your own.

do not deliberately open duplicate issues or you will be blocked from opening further issues
