### ISSUE TITLE
Conflict with youtube-music app

### ISSUE THREAD

**Issue by ameliiom** [Vencord/Vesktop#561]
**Describe the bug**

**To Reproduce**

1. Go to https://github.com/th-ch/youtube-music/releases/tag/v3.3.6 and **install** the .rpm package **(Make sure Vesktop **(.rpm version)** is installed)**
2. U will get a and issue about conflict with the packages 

**Expected behavior**

```
Internal error: Error running transaction: file /usr/lib/.build-id/09/ff65463755b887e71c59f7b68228e92a84bd46 from install of youtube-music-3.3.6-1.x86_64 conflicts with file from package vesktop-1.5.2-1.x86_64
file /usr/lib/.build-id/15/1f079fb274bc8b986bddea21c82a6b2ce21690 from install of youtube-music-3.3.6-1.x86_64 conflicts with file from package vesktop-1.5.2-1.x86_64
file /usr/lib/.build-id/78/e0e100f56ff0ac8894342351a1e880d628eabc from install of youtube-music-3.3.6-1.x86_64 conflicts with file from package vesktop-1.5.2-1.x86_64
file /usr/lib/.build-id/c7/dd943c9a2f9568fcd82fa7baddb1f22f38fb22 from install of youtube-music-3.3.6-1.x86_64 conflicts with file from package vesktop-1.5.2-1.x86_64
file /usr/lib/.build-id/f3/a26db3f1c4644e02d50fa102282631595594df from install of youtube-music-3.3.6-1.x86_64 conflicts with file from package vesktop-1.5.2-1.x86_64
```

**Screenshots**
![image](https://github.com/Vencord/Vesktop/assets/103356505/bbd65c00-3020-420e-b06c-87cff903feda)
![image](https://github.com/Vencord/Vesktop/assets/103356505/702c477d-8c53-4d8a-a4ad-39589935e3a4)

**Desktop (please complete the following information):**
 - OS/Distro: Fedora Linux 
 - Desktop Environment (linux only): KDE
 - Version: 40

**Additional context**
I use the latest version of both app

I don't really know why it happens but I'm pretty sure it's because a signature or shared packages

**Comment by Vendicated** [comment]
same as https://github.com/th-ch/youtube-music/issues/1882

seems to be a common electron + rpm issue. after googling a bit i found
- https://aur.archlinux.org/packages/superproductivity-bin#comment-968181

and this comment mentions workarounds https://github.com/Zettlr/Zettlr/issues/1321#issuecomment-703501960

closing as wontfix because this issue isn't on our side

solution is [here](https://github.com/jordansissel/fpm/issues/1503#issuecomment-404849150) but we can't apply this flag because we don't have control over this process. this issue is likely more appropriate for the electron-builder repo, or some other upstream
