### ISSUE TITLE
Add "--static-files=/path/here/" command-line flag

### ISSUE THREAD

**Issue by Tiagoquix** [Vencord/Vesktop#570]
**Is your feature request related to a problem? Please describe.**
Hi there. I would like to be able to modify the files from the `static` folder from Vesktop without having to recompile the entire program.

**Describe the solution you'd like**
One way to approach this would be to add a command-line flag such as `--static-files=/path/here`.

For example: if I have `--static-files=/home/user/Desktop/Vesktop-Modified/static/` then it would prefer to load those files instead of the original ones. Of course, the files have to be the exact name and extension of the original.

This would also make it possible to modify other notification badge files (ICO), HTML and CSS files.

If the command-line is provided but not all files exist, then it would simple fallback to the original files.

**Describe alternatives you've considered**
Add an option to individually customize `/static/` elements via a GUI, but I don't think that's worth the trouble.
With a command-line option, the approach is simpler.

**Additional context**
I would like to be able to customize the task bar icon and possibly any other thing without having to recompile the program entirely.

![image](https://raw.githubusercontent.com/Vencord/Vesktop/main/static/shiggy.gif)

**Comment by lewisakura** [comment]
This seems like something you should be able to do in your desktop environment...

Either way I don't think it's a good idea to expose this sort of stuff, and it wouldn't be possible to put in the flatpak release of Vesktop either since it would require allowing a holepunch in the sandbox (not good!)

**Comment by Vendicated** [comment]
this makes no sense. at that point just change vesktops files or build from source, it's really not that hard

**Comment by Vendicated** [comment]
why not say that right away :p 

that's more acceptable and i considered something like this, i think there's a different issue for it

**Comment by Vendicated** [comment]
yes that issue, hence why i 👍🏻d that reply proposing the option to modify it

modifying the entire static dir makes little sense because at that point you're basically asking us to add a command line flag to replace source code. it's not very user friendly and awkward to implement in code. you should really just build from source for such modifications!

**Comment by Vendicated** [comment]
sure!
