### ISSUE TITLE
Vesktop crash & restart my PC as soon as logging in

### ISSUE THREAD

**Issue by MalakaiJA** [Vencord/Vesktop#603]
### Discord Account

J.m.a.f.a.a.b.a

### Operating System

Nobara 

### Linux Only ~ Desktop Environment

Wayland 

### What happens when the bug or crash occurs?

Vesktop was disconnecting giving me issue of Java script issue for themes and csnt join voice. Later on I did reset vesktop/vencord & typed my credentials for logging in & suddenly my PC restarts by itself. Did same thing and same sudden restart. Now I don't understand what us up. My PC is modern & current gen. 

### What is the expected behaviour?

It just crash my PC & restart as soon as logging in 

### How do you recreate this bug or crash?

Idk honestly happened after putting another 64 GB of Rams & booted my PC

### Debug Logs

```
Let me first get to be in desktop then sure. 
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
if your pc crashes that's an issue with your system.

**Comment by MalakaiJA** [comment]
This has not happened before to me though. This is recent. Been using vesktop for months now. I don't understand. My PC isn't that old. I built it Janruary 2024....

**Comment by Vendicated** [comment]
your pc's age does not matter. it might be a hardware failure (for example because something isn't properly connected) or just a software failure. you use a linux distro i've never heard of before... it might be a driver, etc

but it's not vesktop. you'll have to figure it out yourself, we can't help more than that! inspect the relevant logs (dmesg, journalctl, etc) or worst case scenario try reinstalling your OS

in any case, that's very out of scope for vesktop. good luck though
