### ISSUE TITLE
[FEATURE REQUEST] Add an option in the settings menu to re-enable opening the menubar through alt

### ISSUE THREAD

**Issue by enderpuff** [Vencord/Vesktop#62]
Quite self explanatory, but that was very useful for me, since i use gnome which doesn't have a decent tray and i'm not a fan of the plugins, so i used the menubar a lot
Please inform me if there is another way to open it that i don't know of

**Comment by Vendicated** [comment]
This can be done, but I personally don't find the menu bar to be very useful so I'm curious what your use case for it is. Maybe there is a better way to incorporate whatever functionality you're missing.


> i'm not a fan of the plugins

what do you mean by that? Vencord plugins? How does the menubar help with that?

Also, which functions of the menu bar do you find useful specifically? I mostly fully disabled since most of what it offers either has a keybind or is somewhat obsolete

**Comment by enderpuff** [comment]
No i meant Gnome plugins to add a Windows-like tray for GNOME
And i used it basically for doing what you'd do with the tray on Windows: Close the app (Not minimize it to the tray), Relaunch, etc..

**Comment by Vendicated** [comment]
for closing you can just control q

**Comment by Vendicated** [comment]
added in https://github.com/Vencord/Vesktop/commit/61f9559984e96ed958cf7e069e149b3221ecaa5e. It'll be in the next update
