### ISSUE TITLE
[Bug] Streaming on Steam Deck produces only audio and a black screen.

### ISSUE THREAD

**Issue by DelDraws19** [Vencord/Vesktop#625]
### Operating System

SteamOS

### What happens when the bug or crash occurs?

My friend cannot get Vesktop streaming to work on his steam deck- we both use it, but for some reason his will not show any games, only stream the audio.

### What is the expected behaviour?

The program is supposed to stream visuals AND audio.

### How do you recreate this bug or crash?

No clue! It's genuinely baffling me and him

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
1. please don't open issues on other people's behalf. proxy help is pain, they should just reach out for help themselves
2. this issue contains 0 relevant info (logs, recording, etc) so it's not possible for us to help
3. issues like this are on your end, caused by your system, often the gpu driver, so they're out of our control. try updating. if that doesn't fix it, observe the terminal logs to find the issue and google it
