### ISSUE TITLE
[Bug] When Vesktop is in the KDE system tray, sometimes clicking on its .desktop will open a new instance of vesktop

### ISSUE THREAD

**Issue by coinkillerl** [Vencord/Vesktop#640]
### Discord Account

@CoinKillerL

### Operating System

CachyOS Linux

### Linux Only ~ Desktop Environment

KDE 6, xwayland

### What happens when the bug or crash occurs?

When vesktop is in the system tray (The window is closed), sometimes clicking on vesktop's .desktop file will start a new instance of vesktop.

### What is the expected behaviour?

Vesktop creates a new window of the already existing Vesktop instance that's present in the system tray.

### How do you recreate this bug or crash?

1. Close the vesktop window.
2. Start vesktop with the .desktop file.

### Debug Logs

```
I can't reproduce this in a consistant way, so i cannot give logs
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
either an issue with your system or with electron, so nothing we can do

**Comment by kimjongbing** [comment]
Hi, I have the exact same issue on Arch Linux using Gnome 46.2 and Mutter (Wayland). The exact reason this happens on Gnome is when you close Vesktop to the system tray in one virtual desktop and then move to another virtual desktop and try open Vesktop from it's ".desktop" file. It doesn't seem to detect Vesktop is still a running application if you open it from a different virtual desktop so it will open a duplicate (that tends to also be logged out from your accounts for some reason). This is a reproducible bug. Not sure if it's because of Electron.

**Comment by TheFeelTrain** [comment]
I am experiencing the same bug. I have to close both windows and then relaunch to fix it every time.

**Comment by Vendicated** [comment]
once again this is not a vesktop issue so commenting here is pointless. locking is implemented by making use of the electron api as described in their docs. make a mininmal reproduction example and report it to electron.

https://github.com/Vencord/Vesktop/blob/af9ed58eef0ced5b4f52bb5be021fc6f71ba7ece/src/main/index.ts#L92-L102
