### ISSUE TITLE
[Bug] Flatpak build is blurry at partial desktop scaling

### ISSUE THREAD

**Issue by Iris-TheRainbow** [Vencord/Vesktop#650]
### Discord Account

@iris_therainbow

### Operating System

KDE Neon 6.0

### Linux Only ~ Desktop Environment

KDE Plasma 6 on wayland

### What happens when the bug or crash occurs?

This is present at all times while vesktop is open while my desktop is at a fractional scaling option (ie 125%, 175%). The whole window is blurry. 

### What is the expected behaviour?

I expect to have sharp text as experienced with the .deb package

### How do you recreate this bug or crash?

Open vesktop with partial scaling enabled

### Request Agreement

- [x] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Iris-TheRainbow** [comment]
@Vendicated Id love to see what makes this an invalid issue, my gpu is a ryzen integrated, so it dont have nvidia and wayland as the cause, and I can give additional information if needed

**Comment by Vendicated** [comment]
> @Vendicated Id love to see what makes this an invalid issue

you would know if you properly read the issue template. it explicitly tells you not to report scaling issues

**Comment by Reonu** [comment]
Hi, I wanna ask a question, and I don't wanna open a whole new issue for it, so I'll ask here. @Iris-TheRainbow @Vendicated 

On my system with the following configuration:
KDE Plasma 9.1 + Wayland + Nvidia RTX 3070 on EndeavourOS

Vesktop looks great at 125% scaling on my main monitor. What doesn't seem to be supported though is per-monitor DPI scaling. Meaning that I have my secondary monitor set to 100% scaling, and when I drag it there, stuff looks smaller, but also blurrier, unlike, say, Firefox, which reacts in real time to being dragged to the secondary screen and everything becomes small AND sharp (ie it immediately sets itself to 100% scaling)

VScode reacts properly to this, just like Firefox, and it's also made with Electron.

Is there some env var or launch argument that I can use so that per-monitor scaling works properly? If not, is this limitation likely to go away soon? Not demanding anything here, just want to know why it doesn't currently work and if there are any concrete plans regarding this.

Thanks!

**Comment by Reonu** [comment]
So turns out all I have to do to fix that issue is to force Vesktop to launch in native Wayland mode. I do wonder why it doesn't already do that by default, but no big deal either way.
