### ISSUE TITLE
[Bug] <Not getting notification popups on Kubuntu 24.04>

### ISSUE THREAD

**Issue by retroDEG** [Vencord/Vesktop#699]
### Discord Account

retrodeg

### Operating System

Kubuntu 24.04

### Linux Only ~ Desktop Environment

KDE X11

### What happens when the bug or crash occurs?

Not getting notification pop ups on desktop or in app. it plays the discord sound, but doesn't pop up.

### What is the expected behaviour?

notification pops up

### How do you recreate this bug or crash?

1. get a notification
2. observe

### Debug Logs

```
Replace this text with your crash-log. Do not remove the backticks
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by retroDEG** [comment]
yes, yes, and yes

**Comment by Vendicated** [comment]
enable desktop notifications in notification settings

if it still doesn't work, system issue

**Comment by Angry-Pineapple3121** [comment]
I am also having this issue on my Fedora system running KDE in Wayland mode.
Desktop notifications are enabled.
`libnotify-0.8.3-3.fc40.x86_64` is installed.
Notifications are working on Discord Stable, Canary and PTB.

Specs/Info:
```
Vesktop 1.5.2
Vencord E37a0cf
Electron 29.1.1
Chromium 122.0.6261.111
Using Canary release channel

Fedora Linux 40 (KDE Plasma) x86_84
Kernal Rev. Linux 6.9.4-200.fc40.x86_64

**Comment by Angry-Pineapple3121** [comment]
Hey @retroDEG, I believe I found the source of the issue. I did some troubleshooting by manually sending notifications through the client (`new Notification("test");` in DevTools, if you want to try), and thought that it may have been my installation platform that was the issue.

I removed my Flatpak installation, and instead installed directly from the rpm package (you've got a [.deb package](https://vencord.dev/download/vesktop/amd64/deb), since you're on Ubuntu), and that appears to have fixed the issue.

I hope that this can help you, as it helped me - just wanted to let you know. :)

**Comment by stankovictab** [comment]
Same issue here, system notifications do not work under Flatpak, even with Vesktop being granted notifications permission via Flatseal. 
@Vendicated this issue should be reopened in my opinion. 
Latest stable Vesktop, Fedora 39, KDE Wayland.

**Comment by Vendicated** [comment]
no. it's an issue with your system. considering everyone here uses kde, it seems like KDE has broken notification portal.
