### ISSUE TITLE
[Bug] Vesktop seems to ignore `~.config/electron-flags.conf`

### ISSUE THREAD

**Issue by Buuugle** [Vencord/Vesktop#938]
### Operating System

Arch Linux

### Linux Only ~ Desktop Environment

Hyprland, Wayland

### Package Type

Tarball

### What happens when the bug or crash occurs?

I use Vesktop on Hyprland. I have two screens with differents resolutions (2560x1440 and 1920x1080). To make theme look the same size, I use a fractonnal scaling of 1.33 on the first one. Since Vesktop runs in XWayland with Electron, I have to use the argument `--enable-features=UseOzonePlatform --ozone-platform=wayland` when I run Vesktop so that it doesn't look blurry. Normally, it's possible to put this flag in `~.config/electron-flags.conf` to make all Electron applications to use it, but Vesktop seems to ignore it because it's blurry anyway.

### What is the expected behaviour?

I expect Vesktop to not be blurry when I put `--enable-features=UseOzonePlatform --ozone-platform=wayland` in `~.config/electron-flags.conf` when using fractionnal scaling on Wayland.

### How do you recreate this bug or crash?

1. Use a fractionnal scaling (for exemple 1.33).
2. Put `--enable-features=UseOzonePlatform --ozone-platform=wayland` in `~.config/electron-flags.conf`.
3. Launch vesktop.
4. It's blurry.

### Debug Logs

```
[bugle@hyprland]$ ./vesktop 
APPIMAGE env is not defined, current application is not an AppImage
checkForUpdatesAndNotify called, downloadPromise is null
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] listening on 6463
[arRPC > process] started
[59177:1029/152234.660379:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by Vendicated** [comment]
For your information, `electron-flags.conf` is not a standard electron feature. It is something the Arch Linux electron packages patch in. Thus, this is expected behaviour and not a bug - this will happen in ANY package that uses official / their own electron instead of the Arch packaged one

Thus, this is not a bug, and also not really possible for us to do unless we use a wrapper script for Vesktop. This shouldn't be done here and instead be up to individual packagers; I believe some AUR vesktop packages do this. Or just make your own
