### ISSUE TITLE
[Bug] There's too much windows

### ISSUE THREAD

**Issue by DankestFke** [Vencord/Vesktop#940]
### Discord Account

ignfeb

### Operating System

Windows 11

### Package Type

Setup exe

### What happens when the bug or crash occurs?

I don't actually know how it happened, probably it happened after launch.

### What is the expected behaviour?

Expected behaviour:
Just one window. If not there's multiple window but be able to close it one by one.

What happened:
There's multiple window running. Closing one window closes all of it (Based on the screenshot given, it only removes one).

![image](https://github.com/user-attachments/assets/e7552319-e89b-4264-8dcc-843a362455ac)

### How do you recreate this bug or crash?

There is two method
**Method 1**
1. Launch Vesktop as startup
2. Boot computer
3. "Vesktop will automatically run"

**Method 2**
1. Launch Vesktop
2. Vesktop finished loading
3. Done

### Debug Logs

```
Checking for update
[12296:1101/220915.531:ERROR:ffmpeg_common.cc(959)] Unsupported pixel format: -1
Update for version 1.5.3 is not available (latest version: 1.5.3, downgrade is disallowed).
checkForUpdatesAndNotify called, downloadPromise is null
```

### Request Agreement

- [x] I have searched the existing issues and found no similar issue
- [X] I am using the latest Vesktop and Vencord versions
- [X] This issue occurs on an official release (not just the AUR or Nix packages)

**Comment by lattaai1** [comment]
Hello, I've fixed this issue!

This is what I've done:
I've identified the issue causing multiple windows to open on launch. The problem appears to be in the `createWindows` function in `src/main/mainWindow.ts`. I've modified this function to ensure only one main window is created and to handle the case of an existing window properly.

Here's a summary of the changes:

1. Added a check to see if a main window already exists before creating a new one.
2. If a main window exists, we now focus and show it instead of creating a new one.
3. Added error handling to prevent crashes if window creation fails.

These changes should resolve the issue of multiple windows opening on launch while maintaining the existing functionality.

I also created pull request: https://github.com/Vencord/Vesktop/pull/941


> [!CAUTION]  
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

**Comment by DankestFke** [comment]
> does it happen on every launch of Vesktop?
It happens every launch of Vesktop.
> Can you make more blank instances when pressing Alt+Tab?
 No, it wont make more blank instances when pressing Alt + Tab, but every time closing and opening vesktop itself (either closing from system tray or by pressing x on the window)
>  Does it happen for other Electron apps, ie; Discord desktop?
IIRC, no. It does not happened to other electron apps like Discord desktop. I had Youtube Music Desktop installed too. 
>  Was this after a recent windows update?
I am not sure for this part. I installed Vesktop after 23H2 update.

**Comment by DankestFke** [comment]
> > I don't know how to run vesktop from command line. (Tried googling how too)
> 
> https://www.wikihow.com/Run-a-Program-on-Command-Prompt
> 
> right click the shortcut, click properties copy the target path (ends in .exe) and paste in command prompt or powershell

Done. I updated the console log

**Comment by Vendicated** [comment]
not an issue with our code so we can't help you, sorry. it's either an issue with your windows or with chrome / electron

**Comment by DankestFke** [comment]
I tried webcord and other electron related clients. Turns out the only problem occured here is Vesktop itself.
