### ISSUE TITLE
[Feature Request] Rebase on ArmCord

### ISSUE THREAD

**Issue by Malix-Labs** [Vencord/Vesktop#956]
### Discord Account

malix_labs

### Motivation

Discord (even with Vesktop) can have bad performance

### Solution

Rebasing vesktop on ArmCord could help with performance

### Alternatives

Staying the same (not rebasing on ArmCord)

### Additional context

I am not aware of the potential drawbacks

### Request Agreement

- [X] I have searched the existing issues and found no similar issue
- [X] This is not a plugin request
- [X] This is not a Vencord feature request

**Comment by Vendicated** [comment]
This request doesn't really make much sense. ArmCord and Vesktop are separate reimplementations of the Discord app, but do many things quite similarly because it's the same framework. Neither of them do anything better than the other which would affect performance in a relevant way

The only thing that would possibly affect performance is enabling many Vencord plugins and themes (especially themes, many themes cause considerable noticeable slowdown)
